_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 13
                - 19
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.10
            "8":
                - 1
                - 5
                - 12
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 64
epochs:
    value: 30
hidden_dim:
    value: 16
input_dim:
    value: 5
lr:
    value: 0.01
output_dim:
    value: 1
